spring.cloud.vault.uri=http://localhost:8200
spring.cloud.vault.token=godis
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.config.import=optional:vault://
spring.cloud.compatibility-verifier.enabled=false
spring.cloud.vault.kv.application-name=boilerroom-labb1