spring.application.name=boilerroom-labb1

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.port=8081
spring.cloud.vault.uri=http://localhost:8200
spring.cloud.vault.token=godis
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.application-name=boilerroom-labb1
spring.cloud.compatibility-verifier.enabled=false
spring.config.import=vault://
jwt.expiration=86400000
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time.to.live=600000
resilience4j.circuitbreaker.instances.openLibrary.sliding-window-size=5
resilience4j.circuitbreaker.instances.openLibrary.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.openLibrary.wait-duration-in-open-state=10s
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true

